In [45]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.impute import SimpleImputer

In [46]:
df=pd.read_csv("/content/LoanApprovalPrediction.csv")

In [47]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [48]:
df["Dependents"] = (
    df["Dependents"]
    .replace("3+", 3)
)

In [50]:
x=df.drop(["Loan_ID","Loan_Status"],axis=1)
y = df["Loan_Status"]

In [51]:
x.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban
1,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural
2,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban
3,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban
4,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban

In [52]:
y.head()

0    Y
1    N
2    Y
3    Y
4    Y
Name: Loan_Status, dtype: object

In [53]:
y = y.map({
    "Y": 1,
    "N": 0
})

# Y → 1  (Approved)
# N → 0  (Rejected)

In [54]:
X_train, X_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [55]:
X_train

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
27,Male,No,0.0,Not Graduate,No,1442,0.0,35.0,360.0,1.0,Urban
443,Male,Yes,0.0,Graduate,No,3948,1733.0,149.0,360.0,0.0,Rural
127,Male,No,0.0,Graduate,Yes,20166,0.0,650.0,480.0,NaN,Urban
400,Male,Yes,1.0,Graduate,No,8300,0.0,152.0,300.0,0.0,Semiurban
279,Male,No,0.0,Graduate,No,3158,3053.0,89.0,360.0,1.0,Rural
...,...,...,...,...,...,...,...,...,...,...,...
486,Male,Yes,1.0,Graduate,Yes,2895,0.0,95.0,360.0,1.0,Semiurban
38,Male,No,0.0,Not Graduate,No,3748,1668.0,110.0,360.0,1.0,Semiurban
331,Female,No,0.0,Graduate,No,4160,0.0,71.0,360.0,1.0,Semiurban
30,Male,No,0.0,Graduate,No,3167,0.0,74.0,360.0,1.0,Urban
396,Female,No,0.0,Graduate,Yes,7441,0.0,194.0,360.0,1.0,Rural

In [56]:
X_test

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
562,Male,Yes,2.0,Graduate,No,3159,461.0,108.0,84.0,1.0,Urban
577,Male,Yes,0.0,Graduate,No,3859,3300.0,142.0,180.0,1.0,Rural
545,Male,Yes,0.0,Graduate,No,3887,2669.0,162.0,360.0,1.0,Semiurban
555,Female,No,0.0,Graduate,No,2378,0.0,9.0,360.0,1.0,Urban
222,Male,Yes,2.0,Graduate,No,6250,1695.0,210.0,360.0,1.0,Semiurban
...,...,...,...,...,...,...,...,...,...,...,...
289,Male,Yes,3.0,Graduate,Yes,4416,1250.0,110.0,360.0,1.0,Urban
472,Male,Yes,2.0,Graduate,No,8333,0.0,246.0,360.0,1.0,Semiurban
213,Male,Yes,2.0,Graduate,Yes,5000,0.0,72.0,360.0,0.0,Semiurban
193,Female,Yes,0.0,Graduate,No,3416,2816.0,113.0,360.0,NaN,Semiurban
376,Male,Yes,2.0,Graduate,No,4566,0.0,100.0,360.0,1.0,Urban

In [69]:
X_train.to_csv("x_train")

In [70]:
X_test.to_csv("x_test")

In [71]:
y_train.to_csv("y_train")

In [72]:
y_test.to_csv("y_test")