In [78]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.impute import SimpleImputer

In [79]:
df=pd.read_csv("/content/LoanApprovalPrediction.csv")

In [80]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [81]:
df["Dependents"] = (
    df["Dependents"]
    .replace("3+", 3)
)

In [82]:
x=df.drop(["Loan_ID","Loan_Status"],axis=1)
y = df["Loan_Status"]

In [83]:
x.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban
1,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural
2,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban
3,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban
4,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban

In [84]:
y.head()

0    Y
1    N
2    Y
3    Y
4    Y
Name: Loan_Status, dtype: object

In [85]:
y = y.map({
    "Y": 1,
    "N": 0
})

# Y → 1  (Approved)
# N → 0  (Rejected)

In [86]:
X_train, X_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [87]:
X_train = X_train.reset_index(drop=True)
X_train

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,Male,No,0.0,Not Graduate,No,1442,0.0,35.0,360.0,1.0,Urban
1,Male,Yes,0.0,Graduate,No,3948,1733.0,149.0,360.0,0.0,Rural
2,Male,No,0.0,Graduate,Yes,20166,0.0,650.0,480.0,NaN,Urban
3,Male,Yes,1.0,Graduate,No,8300,0.0,152.0,300.0,0.0,Semiurban
4,Male,No,0.0,Graduate,No,3158,3053.0,89.0,360.0,1.0,Rural
...,...,...,...,...,...,...,...,...,...,...,...
473,Male,Yes,1.0,Graduate,Yes,2895,0.0,95.0,360.0,1.0,Semiurban
474,Male,No,0.0,Not Graduate,No,3748,1668.0,110.0,360.0,1.0,Semiurban
475,Female,No,0.0,Graduate,No,4160,0.0,71.0,360.0,1.0,Semiurban
476,Male,No,0.0,Graduate,No,3167,0.0,74.0,360.0,1.0,Urban
477,Female,No,0.0,Graduate,Yes,7441,0.0,194.0,360.0,1.0,Rural

In [88]:
X_test = X_train.reset_index(drop=True)
X_test

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,Male,No,0.0,Not Graduate,No,1442,0.0,35.0,360.0,1.0,Urban
1,Male,Yes,0.0,Graduate,No,3948,1733.0,149.0,360.0,0.0,Rural
2,Male,No,0.0,Graduate,Yes,20166,0.0,650.0,480.0,NaN,Urban
3,Male,Yes,1.0,Graduate,No,8300,0.0,152.0,300.0,0.0,Semiurban
4,Male,No,0.0,Graduate,No,3158,3053.0,89.0,360.0,1.0,Rural
...,...,...,...,...,...,...,...,...,...,...,...
473,Male,Yes,1.0,Graduate,Yes,2895,0.0,95.0,360.0,1.0,Semiurban
474,Male,No,0.0,Not Graduate,No,3748,1668.0,110.0,360.0,1.0,Semiurban
475,Female,No,0.0,Graduate,No,4160,0.0,71.0,360.0,1.0,Semiurban
476,Male,No,0.0,Graduate,No,3167,0.0,74.0,360.0,1.0,Urban
477,Female,No,0.0,Graduate,Yes,7441,0.0,194.0,360.0,1.0,Rural

In [89]:
y_train

27     0
443    0
127    1
400    0
279    1
      ..
486    1
38     1
331    1
30     0
396    0
Name: Loan_Status, Length: 478, dtype: int64

In [90]:
y_test

562    1
577    1
545    1
555    0
222    1
      ..
289    1
472    1
213    0
193    1
376    0
Name: Loan_Status, Length: 120, dtype: int64

In [91]:
X_train.to_csv("x_train")

In [92]:
X_test.to_csv("x_test")

In [93]:
y_train.to_csv("y_train")

In [94]:
y_test.to_csv("y_test")